levelToTitle = {
    "Diplomová práce": [ "Mgr.", ],
    "Bakalářská práce": [ "Bc.", ],
    "Rigorózní práce": [ "PhDr.", 'JUDr.', 'RNDr.', 'PharmDr.', 'MUDr.', "ThDr.", ],
    "Habilitační práce": [ "Doc.", ],
    "Dizertační práce": [ 'ThD.', "PhD.", ],
    }

institutToFaculty = {
    'Institut politologických studií': 'Fakulta sociálních věd', 
    'Institut sociologických studií': 'Fakulta sociálních věd',
    'Institut mezinárodních studií': 'Fakulta sociálních věd',
    'Institut ekonomických studií': 'Fakulta sociálních věd',
    }

faculty = {
    'Filozofická fakulta': [
        'Katedra andragogiky',
        'Katedra pomocných věd historických a archivního studia',
        'Ústav etnologie',
        'Katedra andragogiky a personálního řízení',
        'Katedra české literatury a literární vědy',
        'Katedra marxisticko-leninské filosofie',
        'Katedra marxisticko-leninské filozofie',
        'Katedra marxisticko-leninskej filozofie',
        'Katedra marxisticko-leninské sociologie',
        'Katedra pedagogiky',
        'Katedra psychofyziologie a klinické psychologie',
        'Katedra psychologie',
        'Katedra sociologie',
        'Katedra sociologie a filozofie',
        'Katedra sociologie a filosofie',
        'Katedra sociální práce',
        'Katedra tělesné výchovy a sportu',
        'Katedra teorie kultury',
        'Katedra žurnalistiky',
        'Katedra věd o zemích Asie a Afriky',
        'Katedra výchovy a vzdělávání dospělých',
        'Ústav filozofie a religionistiky',
        'Ústav informačních studií a knihovnictví',
        'Katedra psychologie práce a řízení',
        'Katedra klinické psychologie',
        ],
    'Filozoficko-historická fakulta': [ 'Psychologický seminář', ],
    'Fakulta sociálních věd a publicistiky': [ 'Katedra osvěty a výchovy dospělých', ],
    'Fakulta sociálních věd': [
        'Institut politologických studií',
        'Institut sociologických studií',
        'Institut sociologických studií. Katedra sociologie',
        'Institut mezinárodních studií',
        'Institut mezinárodních studií. Katedra západoevropských studií',
        'Institut ekonomických studií',
        'Institut komunikačních studií a žurnalistiky',
        'Institut komunikačních studií a žurnalistiky. Katedra žurnalistiky',
        'Institut komunikačních studií a žurnalistiky. Katedra mediálních studií',
        'Katedra mediálních studií',
        'Katedra veřejné a sociální politiky',
        'Katedra západoevropských studií',
        'Katedra politologie',
        'Katedra amerických studií',
        'Katedra německých a rakouských studií',
        'Katedra mezinárodních vztahů',
        'Katedra sociologie', ],
    'Pedagogická fakulta': [ 
        'Katedra speciální pedagogiky', 
        'Katedra výtvarné výchovy', 
        'Katedra pedagogické a školní psychologie',
        'Katedra informačních technologií a technické výchovy',
        ],
    'Právnická fakulta': [ 
        'Katedra trestního práva',
        'Katedra obchodního práva',
        'Katedra občanského práva',
        'Katedra pracovního práva a práva sociálního zabezpečení',
        'Katedra teorie práva a právních učení',
        'Ústav práva autorského, práv průmyslových a práva soutěžního',
        ],
    'Fakulta humanitních studií': [
        'Katedra elektronické kultury a sémiotiky',
        'Katedra obecné antropologie',
        'Katedra řízení a supervize v sociálních a zdravotnických organizacích', ],
    'Husova evangelická bohoslovecká fakulta': [], #TODO vážně všechny tyhle Husovy',
    'Husova československá evangelická fakulta': [],
    'Husova československá evangelická fakulta bohoslovecká': [],
    'Husova československá evangelická bohoslovecká fakulta': [],
    'Husitská teologická fakulta': [
        'Katedra filosofie',
        'Katedra pedagogiky a psychologie',
        'Katedra psychosociálních věd',
        'Katedra religionistiky',
        'Katedra učitelství',
        'Ústav východního křesťanství',
        'Ústav židovských studií',
        ],
    'Komenského evangelická bohoslovecká fakulta': [
        'Katedra biblických věd',
        'Katedra církevních dějin',
        ],
    'Komenského bohoslovecká fakulta v Praze': [],
    'Evangelická teologická fakulta': [ 
            'Katedra filosofie', 'Katedra sociální teologie', 'Katedra Starého zákona', 
            'Katedra systematické teologie', 'Katedra teologické etiky', 'Katedra sociální pedagogiky',
            'Teologie křesťanských tradic',
            'Katedra pastorační a sociální práce',
            'Katedra sociálně pedagogická',
            'Katedra praktické teologie',
            'Katedra religionistiky',],
    'Matematicko-fyzikální fakulta': [
        'Katedra softwarového inženýrství',
        'Katedra teoretické informatiky a matematické logiky',
        'Kabinet software a výuky informatiky',
        'Ústav formální a aplikované lingvistiky',
        ],
    '1 lékařská fakulta': [],
    '2 lékařská fakulta': [],
    '3 lékařská fakulta': ['Klinika otorinolaryngologická'],
    }
