levelToTitle = {
    "Diplomová práce": [ "Mgr.", ],
    "Bakalářská práce": [ "Bc.", ],
    "Rigorózní práce": [ "PhDr.", 'JUDr.', 'RNDr.', 'PharmDr.', 'MUDr.', "ThDr.", ],
    "Habilitační práce": [ "Doc.", ],
    "Dizertační práce": [ 'ThD.', "PhD.", ],
    }

faculty = {
    'Filozofická fakulta',
    'Filozoficko-historická fakulta',
    'Fakulta sociálních věd a publicistiky',
    'Fakulta sociálních věd',
    'Pedagogická fakulta',
    'Fakulta humanitních studií',
    'Husova evangelická bohoslovecká fakulta', #TODO vážně všechny tyhle Husovy?
    'Husova československá evangelická fakulta',
    'Husova československá evangelická fakulta bohoslovecká',
    'Husova československá evangelická bohoslovecká fakulta',
    'Komenského evangelická bohoslovecká fakulta',
    'Komenského bohoslovecká fakulta v Praze',
    'Evangelická teologická fakulta',
    'Matematicko-fyzikální fakulta',
    '1 lékařská fakulta',
    '2 lékařská fakulta',
    '3 lékařská fakulta',
    }

department = {
    'Katedra sociologie',
    'Katedra psychologie',
    'Katedra speciální pedagogiky',
    'Katedra marxisticko-leninskej filozofie',
    'Institut ekonomických studií',
    'Institut sociologických studií. Katedra sociologie',
    'Katedra výchovy a vzdělávání dospělých',
    'Katedra andragogiky a personálního řízení',
    'Katedra obecné antropologie',
    'Institut sociologických studií',
    'Katedra řízení a supervize v sociálních a zdravotnických organizacích',
    'Ústav informačních studií a knihovnictví',
    'Katedra filosofie',
    'Katedra psychofyziologie a klinické psychologie',
    'Katedra softwarového inženýrství',
    'Ústav filozofie a religionistiky',
    'Katedra nadragogiky a personálního řízení',
    'Katedra tělesné výchovy a sportu',
    'Katedra osvěty a výchovy dospělých',
    'Katedra pedagogiky',
    'Katedra Starého zákona',
    'Institut komunikačních studií a žurnalistiky',
    'Institut komunikačních studií a žurnalistiky. Katedra mediálních studií',
    'Katedra systematické teologie',
    'Katedra socioloogie',
    'Katedra věd o zemích Asie a Afriky',
    'Katedra elektronické kultury a sémiotiky',
    'Katedra teorie kultury',
    'Katedra biblických věd',
    'Katedra české literatury a literární vědy',
    'Katedra sociologie a filozofie',
    'Katedra sociální teologie',
    'Katedra církevních dějin',
    'Katedra marxisticko-leninské sociologie',
    'Katedra teorie kultury',
    'Institut mezinárodních studií. Katedra západoevropských studií',
    'Psychologický seminář',
    'Katedra výtvarné výchovy',
    'Katedra sociologie a filosofie',
    'Institut politologických studií',
    'Katedra marxisticko-leninské filosofie',
    'Katedra andragogika personálního řízení',
    'Katedra teoretické informatiky a matematické logiky',
    }

